export default {
    LOGIN:"LOGIN",
    GET_STATE:"GET_STATE",
    LOGOUT:"LOGOUT",
    GET_PROJECTS:"GET_PROJECTS",
    ADD_PROJECT:"ADD_PROJECT",
    DELETE_PROJECT:"DELETE_PROJECT",
    GET_TIMESHEETS:"GET_TIMESHEETS",
    SELECT_DATE:"SELECT_DATE",
    DELETE_TIMESHEET:"DELETE_TIMESHEET",
    ADD_TIMESHEET:"ADD_TIMESHEET",
    SELECT_MENU:"SELECT_MENU",
    FINISH_PROJECT:"FINISH_PROJECT"
}